x-default_config: &default_config
  network_mode: host
  restart: always
  env_file: ${ENV_FILE}

services:
  mariadb:
    hostname: mariadb1
    container_name: mariadb
    image: mariadb:latest
    ports:
      - ${INTERNAL_IP}:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${CONFIG_FOLDER}/mariadb:/docker-entrypoint-initdb.d
      - ${CONFIG_FOLDER}/mariadb/data:/var/lib/mysql
      - ${CONFIG_FOLDER}/mariadb/backup:/maria_backup
    command: [ '--max_connections=10000' ]
    <<: *default_config
  rabbitmq:
    hostname: rabbitmq1
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - ${INTERNAL_IP}:5672:5672
      - ${INTERNAL_IP}:15672:15672
      - ${INTERNAL_IP}:15692:15692
    environment:
      RABBITMQ_LOG: debug,+color
    ulimits:
      nofile:
        soft: 2000
        hard: 2000
    <<: *default_config
  mongodb:
    hostname: mongo1
    container_name: mongodb
    image: percona/percona-server-mongodb:6.0.14
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    volumes:
      - ${CONFIG_FOLDER}/mongodb/data:/data/db
      - ${CONFIG_FOLDER}/mongodb/backup:/mongo_backup
    command: ["mongod", "--bind_ip", "127.0.0.1,${INTERNAL_IP}", "--port", "27017", "--directoryperdb", "--wiredTigerCacheSizeGB", "1", "--journal", "--keyFile=/data/db/keyFile"]
    <<: *default_config
  reverse_proxy:
    hostname: nginx1
    container_name: reverse_proxy
    image: nginx:latest
    volumes:
      - ${NGINX_CONF_LOCATION}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CONF_LOCATION}/sites:/etc/nginx/sites-enabled
      - ${NGINX_CONF_LOCATION}/ssl/${DOMAIN_NAME}.crt:/etc/ssl/certs/${DOMAIN_NAME}.crt
      - ${NGINX_CONF_LOCATION}/ssl/${DOMAIN_NAME}.key:/etc/ssl/private/${DOMAIN_NAME}.key
    command: ['nginx', '-g daemon off;']
    <<: *default_config
  bind9:
    hostname: bind1
    container_name: bind9
    image: ubuntu/bind9:latest
    volumes:
      - ${BIND_CONF_LOCATION}/db.${DOMAIN_NAME}:/var/cache/bind/db.${DOMAIN_NAME}
      - ${BIND_CONF_LOCATION}/named.conf:/etc/bind/named.conf
      - ${BIND_CONF_LOCATION}/named.conf.access_network:/etc/bind/named.conf.access_network
      # - ${BIND_CONF_LOCATION}/named.conf.system_network:/etc/bind/named.conf.system_network
      - ${BIND_CONF_LOCATION}/named.conf.options:/etc/bind/named.conf.options
    <<: *default_config